%Programa de optimizacao
%X = GA(FITNESSFCN,NVARS,A,b,Aeq,beq,lb,ub,NONLCON,options)
options = optimoptions('ga','PlotFcns',...
 {@gaplotbestf,@gaplotbestindiv,@gaplotexpectation,@gaplotstopping},...
 'PopInitRange',[0;0.9]);
[x fval] = ga(@custo,2,[],[],[1 1],0.9,0,2*pi,[],options)